# Generated by Django 6.1.1 on 2026-09-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitti',
            name='amount_to_be_added',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chitti',
            name='starting_chitti_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='chittimonth',
            constraint=models.UniqueConstraint(fields=('chitti', 'month'), name='unique_chitti_month'),
        ),
    ]
