# Generated by Django 6.1.1 on 2026-09-13 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_chitti_amount_to_be_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('chitti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='money.chitti')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='money.chittimonth')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='money.participant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chitti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='money.chitti')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='money.participant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='money.monthlyobligation')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='money.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='ChittiTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chitti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitti_takes', to='money.chitti')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitti_takes', to='money.chittimonth')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitti_takes', to='money.participant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chitti', 'participant'), name='one_take_per_person_per_chitti'), models.UniqueConstraint(fields=('chitti', 'month'), name='one_take_per_month_per_chitti')],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlyobligation',
            constraint=models.UniqueConstraint(fields=('chitti', 'participant', 'month'), name='unique_monthly_obligation'),
        ),
    ]
