# Generated by Django 6.1.1 on 2026-09-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_monthlyobligation_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chittimonth',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlyobligation',
            name='status_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
